name = newomg
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = newomg-layout

; Regions
regions[ag-test]        = ag-test
regions[ag1]            = ag1
regions[ag2]            = ag2
regions[ag3]            = ag3
regions[ag4]            = ag4
regions[ag5]            = ag5
regions[ag6]            = ag6
regions[ag7]            = ag7
regions[ag8]            = ag8
regions[ag9]            = ag9
regions[ag10]           = ag10


; Stylesheets
stylesheets[all][] = css/newomg.css
